from __future__ import annotations

import math

from exact.type2.schemas import Formula
from exact.type2.solving.units import ureg


def _q(known: dict[str, object], name: str):
    return known[name]


K_COULOMB = 8.9875517923e9 * ureg.newton * (ureg.meter ** 2) / (ureg.coulomb ** 2)


FORMULAS: tuple[Formula, ...] = (
    Formula(
        id="ohm_voltage",
        domain="circuits",
        subfield="dc_circuits",
        target="voltage",
        required=("current", "resistance"),
        output_unit="V",
        expression="U = I * R",
        explanation_template="Ohm's law gives voltage as U = I * R.",
        keywords=("voltage", "current", "resistance", "resistor", "ohm"),
        variables={"U": "voltage", "I": "current", "R": "resistance"},
        conditions=("Ohmic resistor or equivalent DC resistance.",),
        common_mistakes=("Do not multiply voltage by resistance when solving for current.",),
        solve=lambda k: _q(k, "current") * _q(k, "resistance"),
    ),
    Formula(
        id="ohm_current",
        domain="circuits",
        subfield="dc_circuits",
        target="current",
        required=("voltage", "resistance"),
        output_unit="A",
        expression="I = U / R",
        explanation_template="Ohm's law gives current as I = U / R.",
        keywords=("current", "voltage", "resistance", "resistor", "ohm"),
        variables={"I": "current", "U": "voltage", "R": "resistance"},
        conditions=("Ohmic resistor or equivalent DC resistance.",),
        common_mistakes=("Current is voltage divided by resistance, not resistance divided by voltage.",),
        solve=lambda k: _q(k, "voltage") / _q(k, "resistance"),
    ),
    Formula(
        id="ohm_resistance",
        domain="circuits",
        subfield="dc_circuits",
        target="resistance",
        required=("voltage", "current"),
        output_unit="ohm",
        expression="R = U / I",
        explanation_template="Ohm's law gives resistance as R = U / I.",
        keywords=("resistance", "voltage", "current", "resistor", "ohm"),
        variables={"R": "resistance", "U": "voltage", "I": "current"},
        conditions=("Ohmic resistor or equivalent DC resistance.",),
        common_mistakes=("Resistance is voltage divided by current.",),
        solve=lambda k: _q(k, "voltage") / _q(k, "current"),
    ),
    Formula(
        id="power_voltage_current",
        domain="circuits",
        subfield="dc_power",
        target="power",
        required=("voltage", "current"),
        output_unit="W",
        expression="P = U * I",
        explanation_template="Electrical power is P = U * I.",
        keywords=("power", "voltage", "current", "circuit"),
        variables={"P": "power", "U": "voltage", "I": "current"},
        conditions=("Voltage and current refer to the same component or circuit branch.",),
        common_mistakes=("Do not combine voltage and current from different components.",),
        solve=lambda k: _q(k, "voltage") * _q(k, "current"),
    ),
    Formula(
        id="power_current_resistance",
        domain="circuits",
        subfield="dc_power",
        target="power",
        required=("current", "resistance"),
        output_unit="W",
        expression="P = I^2 * R",
        explanation_template="Using Ohm's law, power can be computed as P = I^2 * R.",
        keywords=("power", "current", "resistance", "resistor"),
        variables={"P": "power", "I": "current", "R": "resistance"},
        conditions=("Current and resistance refer to the same resistor.",),
        common_mistakes=("Square the current, not the resistance.",),
        solve=lambda k: (_q(k, "current") ** 2) * _q(k, "resistance"),
    ),
    Formula(
        id="power_voltage_resistance",
        domain="circuits",
        subfield="dc_power",
        target="power",
        required=("voltage", "resistance"),
        output_unit="W",
        expression="P = U^2 / R",
        explanation_template="Using Ohm's law, power can be computed as P = U^2 / R.",
        keywords=("power", "voltage", "resistance", "resistor"),
        variables={"P": "power", "U": "voltage", "R": "resistance"},
        conditions=("Voltage and resistance refer to the same resistor.",),
        common_mistakes=("Square the voltage before dividing by resistance.",),
        solve=lambda k: (_q(k, "voltage") ** 2) / _q(k, "resistance"),
    ),
    Formula(
        id="voltage_from_power_current",
        domain="circuits",
        subfield="dc_power",
        target="voltage",
        required=("power", "current"),
        output_unit="V",
        expression="U = P / I",
        explanation_template="From P = U * I, voltage is U = P / I.",
        keywords=("voltage", "power", "current", "electrical power"),
        variables={"U": "voltage", "P": "power", "I": "current"},
        conditions=("Power and current refer to the same component or circuit branch.",),
        common_mistakes=("Divide power by current to get voltage.",),
        solve=lambda k: _q(k, "power") / _q(k, "current"),
    ),
    Formula(
        id="current_from_power_voltage",
        domain="circuits",
        subfield="dc_power",
        target="current",
        required=("power", "voltage"),
        output_unit="A",
        expression="I = P / U",
        explanation_template="From P = U * I, current is I = P / U.",
        keywords=("current", "power", "voltage", "electrical power"),
        variables={"I": "current", "P": "power", "U": "voltage"},
        conditions=("Power and voltage refer to the same component or circuit branch.",),
        common_mistakes=("Divide power by voltage to get current.",),
        solve=lambda k: _q(k, "power") / _q(k, "voltage"),
    ),
    Formula(
        id="resistance_from_power_current",
        domain="circuits",
        subfield="dc_power",
        target="resistance",
        required=("power", "current"),
        output_unit="ohm",
        expression="R = P / I^2",
        explanation_template="From P = I^2R, resistance is R = P/I^2.",
        keywords=("resistance", "power", "current", "resistor"),
        variables={"R": "resistance", "P": "power", "I": "current"},
        conditions=("Power and current refer to the same resistor.",),
        common_mistakes=("Square the current before dividing.",),
        solve=lambda k: _q(k, "power") / (_q(k, "current") ** 2),
    ),
    Formula(
        id="current_from_power_resistance",
        domain="circuits",
        subfield="dc_power",
        target="current",
        required=("power", "resistance"),
        output_unit="A",
        expression="I = sqrt(P / R)",
        explanation_template="From P = I^2R, current is I = sqrt(P/R).",
        keywords=("current", "power", "resistance", "resistor"),
        variables={"I": "current", "P": "power", "R": "resistance"},
        conditions=("Power and resistance refer to the same resistor.",),
        common_mistakes=("Take the square root after dividing P by R.",),
        solve=lambda k: (_q(k, "power") / _q(k, "resistance")) ** 0.5,
    ),
    Formula(
        id="voltage_from_power_resistance",
        domain="circuits",
        subfield="dc_power",
        target="voltage",
        required=("power", "resistance"),
        output_unit="V",
        expression="U = sqrt(P * R)",
        explanation_template="From P = U^2/R, voltage is U = sqrt(P*R).",
        keywords=("voltage", "power", "resistance", "resistor"),
        variables={"U": "voltage", "P": "power", "R": "resistance"},
        conditions=("Power and resistance refer to the same resistor.",),
        common_mistakes=("Take the square root after multiplying P by R.",),
        solve=lambda k: (_q(k, "power") * _q(k, "resistance")) ** 0.5,
    ),
    Formula(
        id="resistance_from_voltage_power",
        domain="circuits",
        subfield="dc_power",
        target="resistance",
        required=("voltage", "power"),
        output_unit="ohm",
        expression="R = U^2 / P",
        explanation_template="From P = U^2/R, resistance is R = U^2/P.",
        keywords=("resistance", "voltage", "power", "resistor"),
        variables={"R": "resistance", "U": "voltage", "P": "power"},
        conditions=("Voltage and power refer to the same resistor.",),
        common_mistakes=("Square the voltage before dividing by power.",),
        solve=lambda k: (_q(k, "voltage") ** 2) / _q(k, "power"),
    ),
    Formula(
        id="energy_from_power_time",
        domain="circuits",
        subfield="dc_power",
        target="energy",
        required=("power", "time"),
        output_unit="J",
        expression="E = P * t",
        explanation_template="Energy transferred at constant power is E = P * t.",
        keywords=("energy", "power", "time", "electrical energy"),
        variables={"E": "energy", "P": "power", "t": "time"},
        conditions=("Power is constant over the time interval.",),
        common_mistakes=("Use seconds for time when power is in watts.",),
        solve=lambda k: _q(k, "power") * _q(k, "time"),
    ),
    Formula(
        id="power_from_energy_time",
        domain="circuits",
        subfield="dc_power",
        target="power",
        required=("energy", "time"),
        output_unit="W",
        expression="P = E / t",
        explanation_template="Average power is energy transferred per unit time: P = E/t.",
        keywords=("power", "energy", "time", "rate"),
        variables={"P": "power", "E": "energy", "t": "time"},
        conditions=("Average power over the given time interval.",),
        common_mistakes=("Divide energy by time.",),
        solve=lambda k: _q(k, "energy") / _q(k, "time"),
    ),
    Formula(
        id="charge_from_current_time",
        domain="circuits",
        subfield="dc_circuits",
        target="charge",
        required=("current", "time"),
        output_unit="C",
        expression="Q = I * t",
        explanation_template="Electric charge transferred is Q = I * t.",
        keywords=("charge", "current", "time", "flow"),
        variables={"Q": "charge", "I": "current", "t": "time"},
        conditions=("Current is constant over the time interval.",),
        common_mistakes=("Use seconds for time when current is in amperes.",),
        solve=lambda k: _q(k, "current") * _q(k, "time"),
    ),
    Formula(
        id="current_from_charge_time",
        domain="circuits",
        subfield="dc_circuits",
        target="current",
        required=("charge", "time"),
        output_unit="A",
        expression="I = Q / t",
        explanation_template="Current is charge flow per unit time: I = Q / t.",
        keywords=("current", "charge", "time", "flow"),
        variables={"I": "current", "Q": "charge", "t": "time"},
        conditions=("Average current over the given time interval.",),
        common_mistakes=("Divide charge by time, not time by charge.",),
        solve=lambda k: _q(k, "charge") / _q(k, "time"),
    ),
    Formula(
        id="series_resistance",
        domain="circuits",
        subfield="dc_circuits",
        target="resistance",
        required=("resistance", "resistance_2"),
        output_unit="ohm",
        expression="R_eq = R1 + R2",
        explanation_template="For two resistors in series, equivalent resistance is R_eq = R1 + R2.",
        keywords=("series", "equivalent resistance", "resistors"),
        variables={"R_eq": "resistance", "R1": "resistance", "R2": "resistance_2"},
        conditions=("Two resistors connected in series.",),
        common_mistakes=("Do not use the reciprocal formula for series resistors.",),
        solve=lambda k: _q(k, "resistance") + _q(k, "resistance_2"),
    ),
    Formula(
        id="parallel_resistance_two",
        domain="circuits",
        subfield="dc_circuits",
        target="resistance",
        required=("resistance", "resistance_2"),
        output_unit="ohm",
        expression="R_eq = R1 * R2 / (R1 + R2)",
        explanation_template="For two resistors in parallel, R_eq = R1R2/(R1+R2).",
        keywords=("parallel", "equivalent resistance", "resistors"),
        variables={"R_eq": "resistance", "R1": "resistance", "R2": "resistance_2"},
        conditions=("Two resistors connected in parallel.",),
        common_mistakes=("Parallel equivalent resistance is less than either branch resistance.",),
        solve=lambda k: (_q(k, "resistance") * _q(k, "resistance_2"))
        / (_q(k, "resistance") + _q(k, "resistance_2")),
    ),
    Formula(
        id="capacitance_from_charge_voltage",
        domain="capacitance",
        subfield="capacitor_basics",
        target="capacitance",
        required=("charge", "voltage"),
        output_unit="F",
        expression="C = Q / U",
        explanation_template="Capacitance is charge divided by voltage: C = Q / U.",
        keywords=("capacitance", "capacitor", "charge", "voltage"),
        variables={"C": "capacitance", "Q": "charge", "U": "voltage"},
        conditions=("Charge and voltage are across the same capacitor.",),
        common_mistakes=("Use capacitance units, not charge units, for the final answer.",),
        solve=lambda k: _q(k, "charge") / _q(k, "voltage"),
    ),
    Formula(
        id="charge_from_capacitance_voltage",
        domain="capacitance",
        subfield="capacitor_basics",
        target="charge",
        required=("capacitance", "voltage"),
        output_unit="C",
        expression="Q = C * U",
        explanation_template="A capacitor stores charge Q = C * U.",
        keywords=("charge", "capacitor", "capacitance", "voltage"),
        variables={"Q": "charge", "C": "capacitance", "U": "voltage"},
        conditions=("Capacitance and voltage are for the same capacitor.",),
        common_mistakes=("Convert microfarads before multiplying by volts.",),
        solve=lambda k: _q(k, "capacitance") * _q(k, "voltage"),
    ),
    Formula(
        id="voltage_from_charge_capacitance",
        domain="capacitance",
        subfield="capacitor_basics",
        target="voltage",
        required=("charge", "capacitance"),
        output_unit="V",
        expression="U = Q / C",
        explanation_template="For a capacitor, voltage is U = Q / C.",
        keywords=("voltage", "potential difference", "capacitor", "charge", "capacitance"),
        variables={"U": "voltage", "Q": "charge", "C": "capacitance"},
        conditions=("Charge and capacitance are for the same capacitor.",),
        common_mistakes=("Voltage is charge divided by capacitance.",),
        solve=lambda k: _q(k, "charge") / _q(k, "capacitance"),
    ),
    Formula(
        id="capacitor_energy",
        domain="capacitance",
        subfield="capacitor_energy",
        target="energy",
        required=("capacitance", "voltage"),
        output_unit="J",
        expression="W = 1/2 * C * U^2",
        explanation_template="The energy stored in a capacitor is W = 1/2 * C * U^2.",
        keywords=("energy", "stored", "capacitor", "capacitance", "voltage"),
        variables={"W": "energy", "C": "capacitance", "U": "voltage"},
        conditions=("Capacitance and voltage are for the same charged capacitor.",),
        common_mistakes=("Remember the factor 1/2 and square the voltage.",),
        solve=lambda k: 0.5 * _q(k, "capacitance") * (_q(k, "voltage") ** 2),
    ),
    Formula(
        id="capacitor_energy_from_charge_voltage",
        domain="capacitance",
        subfield="capacitor_energy",
        target="energy",
        required=("charge", "voltage"),
        output_unit="J",
        expression="W = 1/2 * Q * U",
        explanation_template="The energy stored in a capacitor can be computed as W = 1/2 * Q * U.",
        keywords=("energy", "stored", "capacitor", "charge", "voltage"),
        variables={"W": "energy", "Q": "charge", "U": "voltage"},
        conditions=("Charge and voltage refer to the same charged capacitor.",),
        common_mistakes=("Remember the factor 1/2.",),
        solve=lambda k: 0.5 * _q(k, "charge") * _q(k, "voltage"),
    ),
    Formula(
        id="capacitor_energy_from_charge_capacitance",
        domain="capacitance",
        subfield="capacitor_energy",
        target="energy",
        required=("charge", "capacitance"),
        output_unit="J",
        expression="W = Q^2 / (2C)",
        explanation_template="The energy stored in a capacitor can be computed as W = Q^2/(2C).",
        keywords=("energy", "stored", "capacitor", "charge", "capacitance"),
        variables={"W": "energy", "Q": "charge", "C": "capacitance"},
        conditions=("Charge and capacitance refer to the same charged capacitor.",),
        common_mistakes=("Square the charge and divide by twice the capacitance.",),
        solve=lambda k: (_q(k, "charge") ** 2) / (2 * _q(k, "capacitance")),
    ),
    Formula(
        id="voltage_from_capacitor_energy_capacitance",
        domain="capacitance",
        subfield="capacitor_energy",
        target="voltage",
        required=("energy", "capacitance"),
        output_unit="V",
        expression="U = sqrt(2W / C)",
        explanation_template="Rearranging W = 1/2CU^2 gives U = sqrt(2W/C).",
        keywords=("voltage", "energy", "capacitor", "capacitance"),
        variables={"U": "voltage", "W": "energy", "C": "capacitance"},
        conditions=("Energy and capacitance refer to the same capacitor.",),
        common_mistakes=("Take the square root after dividing 2W by C.",),
        solve=lambda k: ((2 * _q(k, "energy")) / _q(k, "capacitance")) ** 0.5,
    ),
    Formula(
        id="charge_from_capacitor_energy_capacitance",
        domain="capacitance",
        subfield="capacitor_energy",
        target="charge",
        required=("energy", "capacitance"),
        output_unit="C",
        expression="Q = sqrt(2WC)",
        explanation_template="Rearranging W = Q^2/(2C) gives Q = sqrt(2WC).",
        keywords=("charge", "energy", "capacitor", "capacitance"),
        variables={"Q": "charge", "W": "energy", "C": "capacitance"},
        conditions=("Energy and capacitance refer to the same capacitor.",),
        common_mistakes=("Take the square root after multiplying 2W by C.",),
        solve=lambda k: (2 * _q(k, "energy") * _q(k, "capacitance")) ** 0.5,
    ),
    Formula(
        id="inductor_energy",
        domain="inductance",
        subfield="inductor_energy",
        target="energy",
        required=("inductance", "current"),
        output_unit="J",
        expression="W = 1/2 * L * I^2",
        explanation_template="The magnetic energy stored in an inductor is W = 1/2 * L * I^2.",
        keywords=("energy", "magnetic", "inductor", "inductance", "current"),
        variables={"W": "energy", "L": "inductance", "I": "current"},
        conditions=("Inductance and current are for the same inductor.",),
        common_mistakes=("Remember the factor 1/2 and square the current.",),
        solve=lambda k: 0.5 * _q(k, "inductance") * (_q(k, "current") ** 2),
    ),
    Formula(
        id="electric_field_from_force_charge",
        domain="electrostatics",
        subfield="electric_field",
        target="electric_field",
        required=("force", "charge"),
        output_unit="V/m",
        expression="E = F / q",
        explanation_template="Electric field strength is force per unit charge: E = F / q.",
        keywords=("electric field", "field strength", "force", "charge"),
        variables={"E": "electric_field", "F": "force", "q": "charge"},
        conditions=("Force acts on the same test charge q.",),
        common_mistakes=("Electric field is force divided by charge.",),
        solve=lambda k: _q(k, "force") / _q(k, "charge"),
    ),
    Formula(
        id="electric_field_point_charge",
        domain="electrostatics",
        subfield="coulomb_law",
        target="electric_field",
        required=("charge", "length"),
        output_unit="N/C",
        expression="E = k * |q| / r^2",
        explanation_template="The electric field of a point charge is E = k * |q| / r^2.",
        keywords=("electric field", "point charge", "field", "charge", "distance"),
        variables={"E": "electric_field", "q": "charge", "r": "length"},
        conditions=("Point charge or spherical symmetry; r is the distance from the charge.",),
        common_mistakes=("Use the square of the distance in the denominator.",),
        solve=lambda k: K_COULOMB * abs(_q(k, "charge")) / (_q(k, "length") ** 2),
    ),
    Formula(
        id="electric_field_uniform_from_voltage_distance",
        domain="electrostatics",
        subfield="electric_field",
        target="electric_field",
        required=("voltage", "length"),
        output_unit="V/m",
        expression="E = U / d",
        explanation_template="For a uniform electric field, E = U/d.",
        keywords=("electric field", "voltage", "potential difference", "distance", "uniform"),
        variables={"E": "electric_field", "U": "voltage", "d": "length"},
        conditions=("Uniform electric field between two points or plates separated by distance d.",),
        common_mistakes=("Divide voltage by distance.",),
        solve=lambda k: _q(k, "voltage") / _q(k, "length"),
    ),
    Formula(
        id="voltage_from_uniform_electric_field",
        domain="electrostatics",
        subfield="electric_field",
        target="voltage",
        required=("electric_field", "length"),
        output_unit="V",
        expression="U = E * d",
        explanation_template="For a uniform electric field, potential difference is U = E*d.",
        keywords=("voltage", "potential difference", "electric field", "distance", "uniform"),
        variables={"U": "voltage", "E": "electric_field", "d": "length"},
        conditions=("Uniform electric field along the displacement direction.",),
        common_mistakes=("Multiply field strength by distance.",),
        solve=lambda k: _q(k, "electric_field") * _q(k, "length"),
    ),
    Formula(
        id="electric_potential_point_charge",
        domain="electrostatics",
        subfield="electric_potential",
        target="voltage",
        required=("charge", "length"),
        output_unit="V",
        expression="V = k * q / r",
        explanation_template="The electric potential of a point charge is V = k*q/r.",
        keywords=("electric potential", "voltage", "point charge", "distance"),
        variables={"V": "voltage", "q": "charge", "r": "length"},
        conditions=("Point charge potential relative to infinity.",),
        common_mistakes=("Use r in the denominator, not r squared.",),
        solve=lambda k: K_COULOMB * _q(k, "charge") / _q(k, "length"),
    ),
    Formula(
        id="force_from_field_charge",
        domain="electrostatics",
        subfield="electric_field",
        target="force",
        required=("electric_field", "charge"),
        output_unit="N",
        expression="F = q * E",
        explanation_template="The electric force on a charge in a field is F = q * E.",
        keywords=("electric force", "force", "electric field", "charge"),
        variables={"F": "force", "q": "charge", "E": "electric_field"},
        conditions=("Charge is placed in the given electric field.",),
        common_mistakes=("Use field strength times charge, not divide by charge.",),
        solve=lambda k: _q(k, "charge") * _q(k, "electric_field"),
    ),
    Formula(
        id="coulomb_force",
        domain="electrostatics",
        subfield="coulomb_law",
        target="force",
        required=("charge", "charge_2", "length"),
        output_unit="N",
        expression="F = k * |q1*q2| / r^2",
        explanation_template="Coulomb's law gives the force magnitude as F = k * |q1*q2| / r^2.",
        keywords=("electric force", "force", "charges", "charge", "separated", "distance"),
        variables={"F": "force", "q1": "charge", "q2": "charge_2", "r": "length"},
        conditions=("Point charges or spherically symmetric charges; r is separation distance.",),
        common_mistakes=("Put r squared in the denominator.", "Use both charges, q1 and q2."),
        solve=lambda k: K_COULOMB * abs(_q(k, "charge") * _q(k, "charge_2")) / (_q(k, "length") ** 2),
    ),
    Formula(
        id="coulomb_equal_charges_from_force",
        domain="electrostatics",
        subfield="coulomb_law",
        target="charge",
        required=("force", "length"),
        output_unit="C",
        expression="q = sqrt(F * r^2 / k), for |q1| = |q2| = q",
        explanation_template="For equal point charges, Coulomb's law rearranges to q = sqrt(F*r^2/k).",
        keywords=("charge", "charges", "force", "separated", "q1 = q2", "find q"),
        variables={"q": "charge", "F": "force", "r": "length"},
        conditions=("The two point charges have equal magnitude.",),
        common_mistakes=("Take the square root after solving for q squared.",),
        solve=lambda k: ((_q(k, "force") * (_q(k, "length") ** 2) / K_COULOMB) ** 0.5),
    ),
    Formula(
        id="electric_potential_energy_two_point_charges",
        domain="electrostatics",
        subfield="coulomb_law",
        target="energy",
        required=("charge", "charge_2", "length"),
        output_unit="J",
        expression="U = k * q1 * q2 / r",
        explanation_template="The potential energy of two point charges is U = k * q1 * q2 / r.",
        keywords=("potential energy", "electric potential energy", "charges", "distance", "coulomb"),
        variables={"U": "energy", "q1": "charge", "q2": "charge_2", "r": "length"},
        conditions=("Point charges separated by distance r.",),
        common_mistakes=("Keep the distance in the denominator only once.",),
        solve=lambda k: K_COULOMB * _q(k, "charge") * _q(k, "charge_2") / _q(k, "length"),
    ),
    Formula(
        id="net_force_equal_coulomb_equilateral",
        domain="electrostatics",
        subfield="coulomb_law",
        target="force",
        required=("charge", "length"),
        output_unit="N",
        expression="F_net = sqrt(3) * k * q^2 / r^2",
        explanation_template=(
            "For three equal charges at the vertices of an equilateral triangle, "
            "the two equal Coulomb forces on one charge meet at 60 degrees, so "
            "F_net = sqrt(3) * k*q^2/r^2."
        ),
        keywords=("equilateral", "triangle", "net electric force", "resultant", "coulomb", "charges"),
        variables={"F_net": "force", "q": "charge", "r": "length"},
        conditions=(
            "Three equal point charges at the vertices of an equilateral triangle.",
            "Net force is the magnitude acting on one vertex charge due to the other two.",
        ),
        common_mistakes=("Do not add the two equal force magnitudes as scalars; include the 60 degree angle.",),
        solve=lambda k: math.sqrt(3) * K_COULOMB * (_q(k, "charge") ** 2) / (_q(k, "length") ** 2),
    ),
    Formula(
        id="capacitance_from_energy_voltage",
        domain="capacitance",
        subfield="capacitor_energy",
        target="capacitance",
        required=("energy", "voltage"),
        output_unit="F",
        expression="C = 2W / U^2",
        explanation_template="Rearranging the capacitor energy formula gives C = 2W / U^2.",
        keywords=("capacitance", "capacitor", "energy", "voltage"),
        variables={"C": "capacitance", "W": "energy", "U": "voltage"},
        conditions=("Energy and voltage refer to the same capacitor.",),
        common_mistakes=("Square the voltage before dividing.",),
        solve=lambda k: (2 * _q(k, "energy")) / (_q(k, "voltage") ** 2),
    ),
    Formula(
        id="series_capacitance_two",
        domain="capacitance",
        subfield="capacitor_networks",
        target="capacitance",
        required=("capacitance", "capacitance_2"),
        output_unit="F",
        expression="C_eq = C1 * C2 / (C1 + C2)",
        explanation_template="For two capacitors in series, C_eq = C1C2/(C1+C2).",
        keywords=("series", "equivalent capacitance", "capacitors"),
        variables={"C_eq": "capacitance", "C1": "capacitance", "C2": "capacitance_2"},
        conditions=("Two capacitors connected in series.",),
        common_mistakes=("Series capacitors use the reciprocal rule.",),
        solve=lambda k: (_q(k, "capacitance") * _q(k, "capacitance_2"))
        / (_q(k, "capacitance") + _q(k, "capacitance_2")),
    ),
    Formula(
        id="parallel_capacitance",
        domain="capacitance",
        subfield="capacitor_networks",
        target="capacitance",
        required=("capacitance", "capacitance_2"),
        output_unit="F",
        expression="C_eq = C1 + C2",
        explanation_template="For two capacitors in parallel, equivalent capacitance is C_eq = C1 + C2.",
        keywords=("parallel", "equivalent capacitance", "capacitors"),
        variables={"C_eq": "capacitance", "C1": "capacitance", "C2": "capacitance_2"},
        conditions=("Two capacitors connected in parallel.",),
        common_mistakes=("Do not use the resistor parallel formula for parallel capacitors.",),
        solve=lambda k: _q(k, "capacitance") + _q(k, "capacitance_2"),
    ),
    Formula(
        id="resistivity_from_resistance_area_length",
        domain="circuits",
        subfield="material_properties",
        target="resistivity",
        required=("resistance", "area", "length"),
        output_unit="ohm * meter",
        expression="rho = R * A / l",
        explanation_template="Electrical resistivity is rho = R * A / l.",
        keywords=("resistivity", "resistance", "area", "length", "material"),
        variables={"rho": "resistivity", "R": "resistance", "A": "area", "l": "length"},
        conditions=("Resistance, area, and length refer to the same sample of material.",),
        common_mistakes=("Use area in square meters and length in meters.",),
        solve=lambda k: _q(k, "resistance") * _q(k, "area") / _q(k, "length"),
    ),
    Formula(
        id="resistance_from_resistivity_length_area",
        domain="circuits",
        subfield="material_properties",
        target="resistance",
        required=("resistivity", "length", "area"),
        output_unit="ohm",
        expression="R = rho * l / A",
        explanation_template="Resistance of a uniform wire is R = rho * l / A.",
        keywords=("resistance", "resistivity", "wire", "length", "area"),
        variables={"R": "resistance", "rho": "resistivity", "l": "length", "A": "area"},
        conditions=("Uniform material with constant cross-sectional area.",),
        common_mistakes=("Resistance increases with length and decreases with area.",),
        solve=lambda k: _q(k, "resistivity") * _q(k, "length") / _q(k, "area"),
    ),
)


def retrieve_formulas(
    question: str,
    target: str | None,
    known: dict[str, object],
    preferred_formula_ids: tuple[str, ...] = (),
) -> list[Formula]:
    candidates = [
        formula
        for formula in FORMULAS
        if (target is None or formula.target == target)
        and all(required in known for required in formula.required)
    ]
    preferred = {formula_id: index for index, formula_id in enumerate(preferred_formula_ids)}
    return sorted(
        candidates,
        key=lambda formula: _formula_score(formula, question, preferred),
        reverse=True,
    )


def formula_summary(formula: Formula) -> dict[str, object]:
    return {
        "id": formula.id,
        "domain": formula.domain,
        "subfield": formula.subfield,
        "target": formula.target,
        "required": formula.required,
        "output_unit": formula.output_unit,
        "expression": formula.expression,
        "variables": formula.variables,
        "conditions": formula.conditions,
        "common_mistakes": formula.common_mistakes,
    }


def format_formula_context(formulas: list[Formula]) -> str:
    lines: list[str] = []
    for formula in formulas:
        conditions = "; ".join(formula.conditions) or "No special condition listed."
        mistakes = "; ".join(formula.common_mistakes) or "No common mistake listed."
        lines.append(
            f"- {formula.id} [{formula.domain}/{formula.subfield}]: "
            f"{formula.expression}; required={formula.required}; output={formula.output_unit}; "
            f"conditions={conditions}; common_mistakes={mistakes}"
        )
    return "\n".join(lines)


def _formula_score(
    formula: Formula,
    question: str,
    preferred: dict[str, int] | None = None,
) -> tuple[int, int]:
    lower = question.lower()
    llm_bonus = 0
    if preferred and formula.id in preferred:
        llm_bonus = 1000 - preferred[formula.id]
    keyword_score = sum(1 for keyword in formula.keywords if keyword in lower)
    return (llm_bonus, keyword_score)
